### ISSUE TITLE
RP1210_Set_ISO15765_Flow_Control example

### ISSUE THREAD

**Issue by czechu82** [crow9724/OpenRP1210#2]
Hi,
Can you share an example how to properly set up flow control for 11 bit id 

RP1210_Set_ISO15765_Flow_Control ??

Regards !

**Comment by crow9724** [comment]
Hi,

Below is a quick and dirty example

```
    // can be STANDARD_CAN, EXTENDED_CAN, STANDARD_CAN_ISO15765_EXTENDED, STANDARD_MIXED_CAN_ISO15765 or EXTENDED_CAN_ISO15765_EXTENDED
    unsigned char addressType = STANDARD_CAN;

    // indicates the CAN ID that a flow control response is triggered by
    unsigned int incommingCANID = 0x000007E0;

    // if using STANDARD_CAN_ISO15765_EXTENDED, STANDARD_MIXED_CAN_ISO15765, or EXTENDED_CAN_ISO15765_EXTENDED
    // then this is the extended address byte or network address extension. Otherwise this byte is ignored.
    unsigned char incommingExtAddress = 0x00;

    // CAN ID used in the outgoing flow control message / packets
    unsigned int outgoingCANID = 0x000007E1;

    // same as incommingCANID, but for outgoing packets
    unsigned char outgoingExtAddress = 0x00;
    
    // block size in the outgoing flow control message
    unsigned char blockSize = 0x00;

    // separation time in the outgoing flow control message
    unsigned char stMin = 0x00;

    // sets separation time the interface adapter will use when transmitting
    // the interface will use the greater value of that specified by this parameter
    // and that specified by the ECU for transmit. Set to 0xFFFF to use value reported
    // by the vehicle
    unsigned short stMinTx = 0xFFFF;

    char fpchCommand[15] =
    {
        addressType,
        (incommingCANID & 0xFF000000) >> 24,
        (incommingCANID & 0x00FF0000) >> 16,
        (incommingCANID & 0x0000FF00) >>  8,
        (incommingCANID & 0x000000FF),
        incommingExtAddress,
        (outgoingCANID & 0xFF000000) >> 24,
        (outgoingCANID & 0x00FF0000) >> 16,
        (outgoingCANID & 0x0000FF00) >> 8,
        (outgoingCANID & 0x000000FF),
        outgoingExtAddress,
        blockSize,
        stMin,
        (stMinTx & 0xFF00) >> 8,
        (stMinTx & 0x00FF)
    };

    RP1210_SendCommand(RP1210_Set_ISO15765_Flow_Control, clientId, fpchCommand, 15);
```

Hope that helps!

**Comment by czechu82** [comment]
Thanks for reply !!
This is what  i have with no success

incoming 0x7FE
outgoing 0x7FF

	byte[] fpchClientCommand = new byte[]
	{
		0,
		0,
		0,
		7,
		0xFE,
		0,
		0,
		0,
		7,
		0xFF,
		0,
		0xFF,
		0,
		0xFF,
		0xFF
	};

	ISO15765inst.RP1210_SendCommand(RP1210_Commands.RP1210_Set_ISO15765_Flow_Control, fpchClientCommand, 0xF);
	
	
flow control doesnt work .. Can only send / receive 8 byte long messages.


would you also confirm if the only difference between sending standard vs extended message is byte before ID .
1 for extended and 0 for standard 

0x01 0x18 0xDA 0x1 0xF1  -> for 29 bit ID 
0x00 0x00 0x00 0x7 0xFF  -> standard 11bit


Regards !

**Comment by crow9724** [comment]
That's true if you're sending raw CAN messages (fpchProtocol="CAN" in RP1210_ClientConnect).

I believe to get the flow control to work you have to set fpchProtocol to "ISO15765".

When you do that, the message structure used with SendMessage is:
[Message Type]  [CANID]   [ExtendedAddress]  [MessageData]
    [1 byte]           [ 4 bytes]         [1 byte]             [0-4096 bytes]

Note that nMessageSize is the length of all the bytes above, not just the MessageData.
MessageType is 0 for 11-bit ID and 1 for 29-bit.

Also, be sure that you don't have any filters set that would block messages (RP1210_SendCommand w/ RP1210_Set_All_Filters_States_to_Pass).

**Comment by czechu82** [comment]
thats what i have set up . 15765

i may need your help $

shootme an email once you get a chance 
andy.summers4@aol.com

**Comment by czechu82** [comment]
Solved!!

Filters were causing the issue 


Thanks You !
